// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6o0TaWOBNXikfpqNoR9VIih4Rst9qKbs',
    appId: '1:864824869771:web:c60d3480f7a79f7aca258e',
    messagingSenderId: '864824869771',
    projectId: 'cs4750-fomo-app',
    authDomain: 'cs4750-fomo-app.firebaseapp.com',
    storageBucket: 'cs4750-fomo-app.appspot.com',
    measurementId: 'G-WKVPFW4FSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfL_KB1jHGy2p0J_NP_t3kyYlyrB6f9y4',
    appId: '1:864824869771:android:c30cda9ceed12254ca258e',
    messagingSenderId: '864824869771',
    projectId: 'cs4750-fomo-app',
    storageBucket: 'cs4750-fomo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjmyT5BH-6kyTZX7v63qyjyxOPuKEcX18',
    appId: '1:864824869771:ios:dd9fc5a77c456e03ca258e',
    messagingSenderId: '864824869771',
    projectId: 'cs4750-fomo-app',
    storageBucket: 'cs4750-fomo-app.appspot.com',
    iosClientId: '864824869771-060nfc2trbc0p1rnakrni1f4j4osigni.apps.googleusercontent.com',
    iosBundleId: 'edu.cpp.cs4750.idiaz.project.fomoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjmyT5BH-6kyTZX7v63qyjyxOPuKEcX18',
    appId: '1:864824869771:ios:dd9fc5a77c456e03ca258e',
    messagingSenderId: '864824869771',
    projectId: 'cs4750-fomo-app',
    storageBucket: 'cs4750-fomo-app.appspot.com',
    iosClientId: '864824869771-060nfc2trbc0p1rnakrni1f4j4osigni.apps.googleusercontent.com',
    iosBundleId: 'edu.cpp.cs4750.idiaz.project.fomoApp',
  );
}
